GetProperty:
  handler: ./lambda/GetProperty/index.main
  description: Get property by its Id
  memorySize: 512
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - ${self:custom.DatabaseTable.arn}
  events:
    - http:
        method: GET
        path: /properties/{id}