DeleteTenant:
  handler: ./lambda/DeleteTenant/index.main
  description: "Delete tenant by id and email address"
  memorySize: 512
  timeout: 10 # API Gateway has a timeout of 30 seconds
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.PropertyServiceTable.arn}
  events:
    - http:
        method: delete
        path: /tenants/{id}