service: tenant-service

frameworkVersion: "3"

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  profile: serverless
  region: us-east-1
  logRetentionInDays: 5
  memorySize: 128
  apiName: tenant-service
  timeout: 15
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    TENANT_TABLE_NAME: ${self:custom.TenantsTable.name}
    RENT_PAID_QUEUE: ${self:custom.TenantRentQueue.name}

functions:
  - ${file(./lambda/CreateTenant/config.yml)}
  - ${file(./lambda/UpdateTenant/config.yml)}
  - ${file(./lambda/ListTenants/config.yml)}
  - ${file(./lambda/DeleteTenant/config.yml)}
  - ${file(./lambda/GetTenant/config.yml)}
  - ${file(./lambda/PayRent/config.yml)}
  - ${file(./lambda/PaymentReminder/config.yml)}

resources:
  Resources:
    TenantsTable: ${file(./resources/TenantsTable.yml):TenantTable}
    RentPaidQueue: ${file(./resources/rentQueue.yml):RentPaidQueue}
  Outputs:
    TenantsQueueArn: ${file(./resources/rentQueue.yml):Outputs.RentPaidQueueArn}
    TenantsQueueUrl: ${file(./resources/rentQueue.yml):Outputs.RentPaidQueueUrl}

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function

custom:
  TenantRentQueue:
    name: RentPaidQueue-${self:provider.stage}
    arn: !GetAtt RentPaidQueue.Arn
    url: !Ref RentPaidQueue
  TenantsTable:
    name: !Ref TenantsTable
    arn: !GetAtt TenantsTable.Arn
  esbuild:
    bundle: true
    exclude:
      - aws-sdk
