paymentReminder:
  handler: ./lambda/PaymentReminder/index.main
  description: A function that runs on a schedule to notify tenants that their rents expire in the coming month
  memorySize: 512
  timeout: 10
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - 'arn:aws:dynamodb:us-east-1:*:*'
  events:
    - schedule: cron(0 12 1W * ? *)