paymentReminder:
  handler: ./lambda/PaymentReminder/index.main
  description: A function that reminds tenants that their rents expire in the coming month
  memorySize: 512
  timeout: 10
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - ${self:custom.TenantsTable.arn}
#  events:
#    - schedule: (1 month)