createTenant:
  handler: ./lambda/CreateTenant/index.main
  description: "Create new tenant"
  memorySize: 512
  timeout: 15
#  environment:
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - ${self:custom.TenantsTable.arn}
  events:
    - http:
        method: post
        path: /tenants