GetTenant:
  handler: ./lambda/GetTenant/index.main
  description: "Get tenant by its Id"
  memorySize: 512
  timeout: 10 # API Gateway has a timeout of 30 seconds
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - ${self:custom.DatabaseTable.arn}
  events:
    - http:
        method: GET
        path: /tenants/{id}