TenantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Tenants-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: phone
        AttributeType: S
      - AttributeName: payments
        AttributeType: L
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: phone
        KeySchema:
          - AttributeName: phone
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: payments
        KeySchema:
          - AttributeName: payments
            KeyType: HASH
        Projection:
          ProjectionType: ALL
