sendReminder:
  handler: ./lambda/SendReminder/index.main
  description: A function to notify tenants via SMS that their rent expire in the coming month.
  memorySize: 512
  timeout: 10
  environment:
    SENDER_ID: 'LandLord'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - sns:Publish
      Resource:
        - ${self:custom.PropertyServiceTable.arn}
        - '*'
  events:
    - schedule: cron(0 12 1W * ? *)