SendReminder:
  handler: ./lambda/SendReminder/index.main
  description: Notifies tenants via SMS that their rent will expire in the coming month.
  memorySize: 512
  timeout: 10
  environment:
    SENDER_ID: 'LandLord'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - sns:Publish
      Resource:
        - ${self:custom.PropertyServiceTable.arn}
        - "arn:aws:sns:*:*:*"
  events:
    - schedule: cron(*/3 * * * ? *)
#    - schedule: cron(0 12 1W * ? *)