PropertyServiceTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-${self:provider.stage}-Table
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: notificationDate
        AttributeType: N
      - AttributeName: phone
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    GlobalSecondaryIndexes:
      - IndexName: StatusIndex
        KeySchema:
          - AttributeName: status
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: TenantIndex
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: NotificationDateIndex
        KeySchema:
          - AttributeName: notificationDate
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: PhoneIndex
        KeySchema:
          - AttributeName: phone
            KeyType: HASH
        Projection:
          ProjectionType: ALL