PayRent:
  handler: ./lambda/PayRent/index.main
  description: "Pay rent"
  memorySize: 512
  timeout: 10 # API Gateway has a timeout of 30 seconds
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - !Join ["/", ["${self:custom.DatabaseTable.arn}", "index", "*"]]
        - ${self:custom.DatabaseTable.arn}
  events:
    - http:
        method: POST
        path: /tenants/{id}/pay