PayRent:
  handler: ./lambda/PayRent/index.main
  description: "Pay rent"
  memorySize: 512
  timeout: 10 # API Gateway has a timeout of 30 seconds
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - "arn:aws:dynamodb:*:*:*"
#        - ${self:custom.PropertyServiceTable.arn}
  events:
    - http:
        method: post
        path: /tenants/{id}/pay