ListTenants:
  handler: ./lambda/ListTenants/index.main
  description: "Fetches tenants by status"
  memorySize: 512
  timeout: 10
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: !Join ["/", ["${self:custom.PropertyServiceTable.arn}", "index", "*"]]
  events:
    - http:
        method: GET
        path: /tenants