ListTenants:
  handler: ./lambda/ListTenants/index.main
  description: "Fetches all the saved tenant"
  memorySize: 512
  timeout: 10 # API Gateway has a timeout of 30 seconds
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - ${self:custom.PropertyServiceTable.arn}
  events:
    - http:
        method: get
        path: /tenants