ListTenants:
  handler: ./lambda/ListTenants/index.main
  description: "Fetches all the saved tenant based on their status"
  memorySize: 512
  timeout: 10
  environment:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:*:*:*"
  events:
    - http:
        method: get
        path: /tenants