ListProperties:
  handler: ./lambda/ListProperties/index.main
  description: Fetches properties by status
  memorySize: 512
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: !Join ["/", ["${self:custom.DatabaseTable.arn}", "index", "*"]]
  events:
    - http:
        method: GET
        path: /properties