UpdateTenantOnPayment:
  handler: ./lambda/UpdateTenantOnPayment/index.main
  description: Update the notification date for the tenant
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.PropertyServiceTable.arn}
  events:
    - stream:
        type: dynamodb
        arn: ${self:custom.PropertyServiceTableStream.arn}
        filterPatterns:
          - eventName: [INSERT]
            dynamodb:
              NewImage:
                Type:
                  S: [Payment]