SendPaymentNotification:
  handler: ./lambda/SendPaymentNotification/index.main
  description: Sends payment confirmation SMS to tenant after rent is paid
  memorySize: 128
  timeout: 10
  environment:
    SENDER_ID: LandLord
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - sns:Publish
      Resource:
        - ${self:custom.DatabaseTable.arn}
        - 'arn:aws:sns:*:*:*'
  events:
    - stream:
        type: dynamodb
        arn: ${self:custom.DatabaseTable.streamArn}
        filterPatterns:
          - eventName: [INSERT]
            dynamodb:
              NewImage:
                Type:
                  S: [Payment]
